### ISSUE TITLE
new user error

### ISSUE THREAD

**Issue by epreom** [GNUWorldChannel/cservice-web-php7.4#2]
Hello, can you help me, it gives an error at the last stage when creating a new user, screenshot is attached.
![error](https://github.com/GNUWorldChannel/cservice-web-php7.4/assets/38203571/dfce1881-ea5e-42cf-99d5-43c879ffd7ef)

**Comment by unixfool** [comment]
Download, Undernet CService Web from the oficial github. Just follow this guide for install.
